from django.db import migrations, models
import taggit.managers
import utilities.json

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS netbox_component_synchronization_componentsyncpermission (
                        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        "created" timestamptz NULL,
                        "last_updated" timestamptz NULL,
                        "description" varchar(200) NOT NULL DEFAULT '',
                        "custom_field_data" jsonb NOT NULL DEFAULT '{}'::jsonb
                    );
                    """,
                    reverse_sql="DROP TABLE IF EXISTS netbox_component_synchronization_componentsyncpermission;"
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='ComponentSyncPermission',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                        ('created', models.DateTimeField(auto_now_add=True, null=True)),
                        ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                        ('description', models.CharField(blank=True, max_length=200)),
                        ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                        ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                    ],
                    options={
                        'verbose_name': 'Synchronize Button',
                        'verbose_name_plural': 'Synchronize Button',
                        'permissions': (('can_use', 'Can use component sync tools'),),
                    },
                ),
            ],
        ),
    ]
